services:
    server:
        build: ./server
        ports:
            - 5050:5000
        command: npm run dev
        volumes:
            - ./server/src:/app/src
        depends_on:
            - mongodb
    client:
        build: ./client
        ports:
            - 58080:3000
        volumes:
            - ./client/src:/app/src
            - ./client/public:/app/public
        command: npm start
        depends_on:
            - server
    mongodb:
        image: mongo
        volumes:
            - ./data/db:/data/db
